### ISSUE TITLE
没找到CNN数据集

### ISSUE THREAD

**Issue by Rafael8830** [zjunlp/SemEval2021Task4#1]
您好！请问"./dataset/cnn-daily/train.txt"数据集在哪里获取呢？

**Comment by zxlzr** [comment]
您好，这个项目没有这个路径，您是不是看错了

**Comment by Rafael8830** [comment]
我看到pretrain_model.sh中的TRAIN_FILE和VAL_FILE的路径就是cnn-daily文件夹，如果不添加该文件夹运行pretrain_model.sh的话会报错。

pretrain_model.sh文件内容：
model="roberta-large"
MODEL_NAME_OR_PATH="/home/xx/pretrained_model/"${model}
TRAIN_FILE="./dataset/cnn-daily/train.txt"
VAL_FILE="./dataset/cnn-daily/val.txt"
OUTPUT_DIR="./output/pretrain_test3"
CUDA_VISIBLE_DEVICES=0 python    \
 ./pretrain/pretrain.py \
    --model_name_or_path $MODEL_NAME_OR_PATH \
    --model_type roberta \
    --train_data_file $TRAIN_FILE \
    --eval_data_file $VAL_FILE \
    --do_train \
    --do_eval \
    --num_train_epochs 4 \
    --learning_rate  1e-6 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --output_dir $OUTPUT_DIR \
    --mlm \
    --line_by_line  \
    --block_size 256 \
    --save_steps 20000 

报错信息如下：
Traceback (most recent call last):
  File "./pretrain/pretrain.py", line 342, in <module>
    main()
  File "./pretrain/pretrain.py", line 269, in main
    get_dataset(data_args, tokenizer=tokenizer, cache_dir=model_args.cache_dir) if training_args.do_train else None
  File "./pretrain/pretrain.py", line 168, in get_dataset
    return _dataset(args.train_data_file, args.train_ref_file)
  File "./pretrain/pretrain.py", line 153, in _dataset
    return LineByLineTextDataset(tokenizer=tokenizer, file_path=file_path, block_size=args.block_size, args=args)
  File "/mdata/zxchen/SemEval2021Task4/pretrain/pretrain_utils.py", line 168, in __init__
    assert os.path.isfile(file_path), f"Input file path {file_path} not found"
AssertionError: Input file path ./dataset/cnn-daily/train.txt not found

**Comment by CheaSim** [comment]
本项目没有放置数据集，请在[cnn daily](https://huggingface.co/datasets/cnn_dailymail) 中下载数据集，并放置在`dataset/cnn-daily`中。

**Comment by zxlzr** [comment]
请问您问题解决了吗

**Comment by Rafael8830** [comment]
解决了谢谢！
